In [ ]:
import numpy as np
import pandas as pd

In [ ]:
xTrain = pd.read_csv("/content/digits_training_data.csv", header = None)
yTrain = pd.read_csv("/content/digits_training_labels.csv", header = None)
xTest = pd.read_csv("/content/digits_test_data.csv", header = None)
yTest = pd.read_csv("/content/digits_test_labels.csv", header = None)

In [ ]:
print(xTrain.shape[0])

1000


In [ ]:
lambda1 = 0
mu1 = 0
mu2 = 0
sigma = 0
count1 = 0
for i in range(len(yTrain)):
  if(yTrain[0][i] == 1):
    lambda1 += 1
    count1 += 1
lambda1 /= len(yTrain)
count2 = 1000 - count1
#print(lambda1)

for i in range(len(yTrain)):
  if(yTrain[0][i] == 1):
    mu1 += xTrain.transpose()[i]
  else:
    mu2 += xTrain.transpose()[i]

mu1 /= count1
mu2 /= count2

#print(mu1)
#print(mu2)

for i in range(len(yTrain)):
  if(yTrain[0][i] == 1):
    sigma += np.outer((xTrain.transpose()[i] - mu1),(xTrain.transpose()[i] - mu1))
  else:
    sigma += np.outer((xTrain.transpose()[i] - mu2),(xTrain.transpose()[i] - mu2))

sigma /= len(yTrain)
print(sigma.shape)
for i in range(len(sigma)):
  sigma[i][i] += .000000001
print(sigma)
sigmaInv = np.linalg.inv(sigma)


(676, 676)
[[1.e-09 0.e+00 0.e+00 ... 0.e+00 0.e+00 0.e+00]
 [0.e+00 1.e-09 0.e+00 ... 0.e+00 0.e+00 0.e+00]
 [0.e+00 0.e+00 1.e-09 ... 0.e+00 0.e+00 0.e+00]
 ...
 [0.e+00 0.e+00 0.e+00 ... 1.e-09 0.e+00 0.e+00]
 [0.e+00 0.e+00 0.e+00 ... 0.e+00 1.e-09 0.e+00]
 [0.e+00 0.e+00 0.e+00 ... 0.e+00 0.e+00 1.e-09]]


In [ ]:

predictions = list()
for i in range(len(xTest)):
  funcG = np.dot(np.dot(sigmaInv, (mu1 - mu2)), xTest.transpose()[i]) + (1/2 * np.dot(np.dot(mu2.transpose(),(sigmaInv)),mu2)) - (1/2 * np.dot(np.dot(mu1.transpose(),sigmaInv),mu1)) + (np.log(lambda1/(1-lambda1)))
  prediction = 1/(1 + np.exp(- funcG))
  if funcG  <= .5:
    predictions.append(-1)
  else:
    predictions.append(1)

correct = 0
for i in range(len(yTest)):
  if predictions[i] == yTest[0][i]:
    correct += 1

print(f"Test Error: {correct/len(yTest)}%")


predictions = list()
for i in range(len(xTrain)):
  funcG = np.dot(np.dot(sigmaInv, (mu1 - mu2)), xTrain.transpose()[i]) + (1/2 * np.dot(np.dot(mu2.transpose(),(sigmaInv)),mu2)) - (1/2 * np.dot(np.dot(mu1.transpose(),sigmaInv),mu1)) + (np.log(lambda1/(1-lambda1)))
  prediction = 1/(1 + np.exp(- funcG))
  if funcG  <= .5:
    predictions.append(-1)
  else:
    predictions.append(1)


correct = 0
for i in range(len(yTrain)):
  if predictions[i] == yTrain[0][i]:
    correct += 1

print(f"Train Error: {correct/len(yTrain)}%")


<ipython-input-49-909430e47ace>:6: RuntimeWarning: overflow encountered in exp
  prediction = 1/(1 + np.exp(- funcG))


Test Error: 0.894%
Train Error: 0.998%


In [ ]:
predictions = list()

for i in range(len(xTest)):
  p1 = lambda1 * np.exp(-1/2 * np.dot(np.dot((xTest.transpose()[0] - mu1).transpose(), (np.linalg.inv(sigma))), (xTest.transpose()[0] - mu1)) )
  p2 = (1- lambda1) * np.exp(-1/2 * np.dot(np.dot((xTest.transpose()[0] - mu2).transpose(), (np.linalg.inv(sigma))), (xTest.transpose()[0] - mu2)) )
  if p1 >= p2:
    predictions.append(1)
  else:
    predictions.append(-1)

In [ ]:
count = 0
for i in range(len(xTest)):
  if yTest[0][i] != predictions[i]:
    print(f"Missclassified the {i+1}th digit")
    if yTest[0][i] == 1:
      print("Digit was 9, but was classified as 4")
    else:
      print("Digit was 4, but was classified as 9")
    count += 1
  if count == 5:
    break


Missclassified the 1th digit
Digit was 9, but was classified as 4
Missclassified the 2th digit
Digit was 4, but was classified as 9
Missclassified the 4th digit
Digit was 4, but was classified as 9
Missclassified the 6th digit
Digit was 4, but was classified as 9
Missclassified the 9th digit
Digit was 4, but was classified as 9
